# Generated by Django 6.1.1 on 2026-09-30 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_requirements_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alternatives',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('alternatives', 'Alternatives')], default='pending', max_length=20),
        ),
    ]
